### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [blood pressure monitor/Meta](https://hosted.weblate.org/projects/blood-pressure-monitor-fl/meta/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Thanhngoclitmax** [comment]
weblate

**Comment by NobodyForNothing** [comment]
@Thanhngoclitmax could you stop writing random participants names in discussions? Unless you provide a valid explanation I will delete those messages and treat you as a bot.

**Review by derdilla — APPROVED** [review]

**Pull request merged**
